
-- HUMANLIST 테이블 생성
CREATE TABLE HUMANLIST
(
  MID NUMBER NOT NULL
, NAME VARCHAR2(10) 
, TELEPHONE VARCHAR2(30)
, CONSTRAINT MEM_PK_MID PRIMARY KEY(MID)
);


-- HUMANLIST_SEQ 시퀀스 생성 
CREATE SEQUENCE HUMANLIST_SEQ
INCREMENT BY 1 MAXVALUE 5000 CYCLE;

-- HUMANLIST 테이블 조회
SELECT *
FROM HUMANLIST;

-- 한줄 작성
SELECT * FROM HUMANLIST;

-- HUMANLIST 갯수 조회
SELECT COUNT(*)
FROM HUMANLIST;

-- 한줄 작성
SELECT COUNT(*) FROM HUMANLIST;

-- HUMANDAO add 메소드에 적용할 인서트 문 작성
-- 처리할 내용이 아니기에 주석처리
-- INSERT INTO HUMANLIST(NAME, TELEPHONE)
-- VALUES(HUMANLIST_SEQ.NEXTVAL, ?,?);

-- 한줄 작성
-- INSERT INTO HUMANLIST(NAME, TELEPHONE) VALUES(HUMANLIST_SEQ.NEXTVAL, ?, ?);